export const DUMMY_SONGS = [
	{
		id: '1',
		title: 'Song One',
		artist: 'Artist One',
		album: 'Album One',
		cover: '/image.png',
	},
	{
		id: '2',
		title: 'Song Two',
		artist: 'Artist Two',
		album: 'Album Two',
		cover: '/image.png',
	},
	{
		id: '3',
		title: 'Song Three',
		artist: 'Artist Three',
		album: 'Album Three',
		cover: '/image.png',
	},
	{
		id: '4',
		title: 'Song Four',
		artist: 'Artist Four',
		album: 'Album Four',
		cover: '/image.png',
	},
	{
		id: '5',
		title: 'Song Five',
		artist: 'Artist Five',
		album: 'Album Five',
		cover: '/image.png',
	},
	{
		id: '6',
		title: 'Song Six',
		artist: 'Artist Six',
		album: 'Album Six',
		cover: '/image.png',
	},
	{
		id: '7',
		title: 'Song Seven',
		artist: 'Artist Seven',
		album: 'Album Seven',
		cover: '/image.png',
	},
	{
		id: '8',
		title: 'Song Eight',
		artist: 'Artist Eight',
		album: 'Album Eight',
		cover: '/image.png',
	},
	{
		id: '9',
		title: 'Song Nine',
		artist: 'Artist Nine',
		album: 'Album Nine',
		cover: '/image.png',
	},
	{
		id: '10',
		title: 'Song Ten',
		artist: 'Artist Ten',
		album: 'Album Ten',
		cover: '/image.png',
	},
];
